### PR TITLE
Try to merge master in a PR before we verify changes.

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
We are now trying to merge `master` in each PR branch before we run `verifyChanges` logic.
If the merge is successful we will `git diff` with `--staged` so we check our local staged changes after merge against changeTarget.
If the merge is not successful we will revert to the old logic of verifying changes.

### CODE REVIEW

**Comment by WardBrian** [comment]
Is there any good way to test this before merging?

**Comment by serban-nicusor-toptal** [comment]
I've re-run [an old job](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-1004/7/pipeline/12) with the new code and also tested it locally to check 90% of the edge cases.
Jenkins also allows us to run a project with a specific version/branch of the shared libraries but I'm not entire sure who can be our test subject as we would need a PR made from a repo branch and a PR from a forked origin.

**Comment by WardBrian** [comment]
I think ideally we would test with something that should merge automatically. Something like https://github.com/stan-dev/stanc3/pull/980 should merge fine, but was last updated before a change to stan_math_signatures. This would be a good test to see if it runs the expression tests or not.

**Comment by WardBrian** [comment]
https://github.com/stan-dev/stanc3/pull/1029 could also qualify, and is from a forked origin

**Comment by serban-nicusor-toptal** [comment]
See [#980](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-980/16/pipeline/12) run

**Comment by WardBrian** [comment]
I'm not seeing any merge commands in that run?

**Comment by serban-nicusor-toptal** [comment]
See [latest run](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-980/27/pipeline/12)

**Comment by WardBrian** [comment]
Seems like the build step is now failing as a result?

**Comment by serban-nicusor-toptal** [comment]
Yes, the merge is leaving some untracked files. Fixing it with a hard reset or force checkout.

**Comment by serban-nicusor-toptal** [comment]
I think it's working as expected now.
See stanc3 [branch](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-980/41/pipeline/12/) and [fork](https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-1029/8/pipeline/12).
Keep in mind that in the above pipelines the math signature tests ran because the build [was a reply](https://github.com/stan-dev/jenkins-shared-libraries/blob/master/src/org/stan/Utils.groovy#L148).
We can see in Jenkins logs that it doesn't find changes there anymore after the merge with master.
image
image

**Review by WardBrian — APPROVED** [review]

**Pull request merged**
